import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* use 'antialiased' to control how font characters are rendered on the screen and smoothing the font */}
      <body className='antialiased' >{children}</body>
    </html>
  )
}
